# Generated by Django 5.1.6 on 2025-08-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_quizattempt_useranswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpdf",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
